### ISSUE TITLE
DB連携

### ISSUE THREAD

**Issue by matyahiko2831** [pink-elephant2/cheese-sns-api#2]

**Comment by c5apple** [comment]
後々検討でもいいです。
batch側でも同じDB使うので、common.jarみたいな感じで読み込めたら捗りそうですね。

**Comment by c5apple** [comment]
>後々検討でもいいです。
>batch側でも同じDB使うので、common.jarみたいな感じで読み込めたら捗りそうですね。

@matyahiko2831 
こちら、commonリポジトリ作ったのでそちらへ移行していきたい。
別issue作ります。
